#!/usr/bin/bash

# Enviroment
APP_NAME="discup"
APP_DESCRIPTION="A dump script to update the discord in linux."
APP_VERSION="0.3.0"
APP_OWNER="SadS4ndWiCh"

# Colors
CL_RESET="\033[0m"
CL_ERROR="\033[0;31m"
CL_SUCCESS="\033[0;32m"
CL_INFO="\033[1;33m"

# Discord
DISCORD_URL_DOWNLOAD="https://discord.com/api/download?platform=linux"
DISCORD_DOWNLOAD_OUTPUT=/tmp/discord.deb

# Utils functions
log_success() {
    echo -e "[$CL_SUCCESS+$CL_RESET] OK: $1"
}
log_error() {
    echo -e "[$CL_ERROR-$CL_RESET] ERROR: $1"
}
log_info() {
    echo -e "[$CL_INFO*$CL_RESET] INFO: $1"
}

cat <<'END_HEADER'
       ....             .       .x+=:.                                          
   .xH888888Hx.        @88>    z`    ^%                                         
 .H8888888888888:      %8P        .   <k              x.    .      .d``         
 888*"""?""*88888X      .       .@8Ned8"       .    .@88k  z88u    @8Ne.   .u   
'f     d8x.   ^%88k   .@88u   .@^%8888"   .udR88N  ~"8888 ^8888    %8888:u@88N  
'>    <88888X   '?8  ''888E` x88:  `)8b. <888'888k   8888  888R     `888I  888. 
 `:..:`888888>    8>   888E  8888N=*8888 9888 'Y"    8888  888R      888I  888I 
        `"*88     X    888E   %8"    R88 9888        8888  888R      888I  888I 
   .xHHhx.."      !    888E    @8Wou 9%  9888        8888 ,888B .  uW888L  888' 
  X88888888hx. ..!     888&  .888888P`   ?8888u../  "8888Y 8888"  '*88888Nu88P  
 !   "*888888888"      R888" `   ^"F      "8888P'    `Y"   'YP    ~ '88888F`    
        ^"***"`         ""                  "P'                      888 ^      
                                                                     *8E        
                                                                     '8>        
                                                                      "         
END_HEADER

echo $APP_DESCRIPTION
echo "Developed by $APP_OWNER ~ Version $APP_VERSION"
echo ""

log_info "Downloading latest discord version..."

curl -s -f -L $DISCORD_URL_DOWNLOAD -o $DISCORD_DOWNLOAD_OUTPUT &> /dev/null
if [[ ! $? -eq 0 ]]; then
    log_error "Failed to download discord"
    log_error "Maybe the discord server went down or the download link changes"
    log_error "Used URL: $DISCORD_URL_DOWNLOAD"
    exit $?
fi

log_success "Discord was downloaded successfuly"
log_info "Installing discord..."

sudo -p "[*] ROOT: Type the user password: " dpkg -i $DISCORD_DOWNLOAD_OUTPUT &> /dev/null
if [[ ! $? -eq 0 ]]; then
    log_error "Failed to install discord"
    log_error "Run the following command by yourself: dpkg -i $DISCORD_DOWNLOAD_OUTPUT"
    exit $?
fi

log_success "Discord was installed successfuly"

log_info "Removing discord installer"

rm $DISCORD_DOWNLOAD_OUTPUT

if [[ ! $? -eq 0 ]]; then
    log_error "Failed to remove discord installer"
    log_error "Run the following command by yourself: rm -fr $DISCORD_DOWNLOAD_OUTPUT"
else
    log_success "Temp discord installer was successfuly removed"
fi

log_success "Open discord by typing \"discord\""
